# Generated by Django 6.0.1 on 2026-01-28 05:18

import django.db.models.deletion
import migration.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Identificador único del requisito (ej: ci)', max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del requisito (ej: Cédula de Identidad)', max_length=150, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
            ],
            options={
                'verbose_name': 'Tipo de Requisito',
                'verbose_name_plural': 'Tipos de Requisito',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoVisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Identificador único del tipo de visa (ej: estudiantil)', max_length=30, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del tipo de visa (ej: Estudiantil)', max_length=100, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
            ],
            options={
                'verbose_name': 'Tipo de Visa',
                'verbose_name_plural': 'Tipos de Visa',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': 'Agentes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='Nombre')),
                ('cedula', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Cédula')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('tipo_visa', models.CharField(blank=True, max_length=30, verbose_name='Tipo de Visa')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitante',
                'verbose_name_plural': 'Solicitantes',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisado', 'Revisado'), ('faltante', 'Faltante')], default='faltante', max_length=20, verbose_name='Estado')),
                ('carga_habilitada', models.BooleanField(default=True, verbose_name='Carga Habilitada')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='migration.solicitante')),
            ],
            options={
                'verbose_name': 'Requisito',
                'verbose_name_plural': 'Requisitos',
                'ordering': ['solicitante', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(verbose_name='Inicio')),
                ('fin', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('exitosa', 'Exitosa'), ('cancelada', 'Cancelada'), ('fallida', 'Fallida')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='migration.agente')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='migration.solicitante')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('cerrada_aceptada', 'Cerrada Aceptada'), ('cerrada_rechazada', 'Cerrada Rechazada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('solicitante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carpeta', to='migration.solicitante')),
            ],
            options={
                'verbose_name': 'Carpeta',
                'verbose_name_plural': 'Carpetas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='RequisitoVisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden en que se muestra el requisito para este tipo de visa', verbose_name='Orden')),
                ('obligatorio', models.BooleanField(default=True, verbose_name='Obligatorio')),
                ('tipo_requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visas_requisito', to='migration.tiporequisito')),
                ('tipo_visa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_visa', to='migration.tipovisa')),
            ],
            options={
                'verbose_name': 'Requisito por Visa',
                'verbose_name_plural': 'Requisitos por Visa',
                'ordering': ['tipo_visa', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versión')),
                ('archivo', models.FileField(blank=True, null=True, upload_to=migration.models.generar_ruta_documento, verbose_name='Archivo subido')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisado', 'Revisado'), ('faltante', 'Faltante')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='migration.requisito')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('requisito', 'version'), name='uniq_requisito_version')],
            },
        ),
        migrations.AddConstraint(
            model_name='requisito',
            constraint=models.UniqueConstraint(fields=('solicitante', 'nombre'), name='uniq_solicitante_requisito'),
        ),
        migrations.AddConstraint(
            model_name='requisitovisa',
            constraint=models.UniqueConstraint(fields=('tipo_visa', 'tipo_requisito'), name='uniq_tipovisa_tiporequisito'),
        ),
    ]
