# Generated by Django 6.0.1 on 2026-01-25 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitante',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cédula'),
        ),
        migrations.AddField(
            model_name='solicitante',
            name='tipo_visa',
            field=models.CharField(blank=True, choices=[('estudiantil', 'Estudiantil'), ('trabajo', 'Trabajo'), ('residencial', 'Residencial'), ('turista', 'Turista')], max_length=20, null=True, verbose_name='Tipo de Visa'),
        ),
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('solicitante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carpeta', to='migration.solicitante')),
            ],
            options={
                'verbose_name': 'Carpeta',
                'verbose_name_plural': 'Carpetas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisado', 'Revisado'), ('faltante', 'Faltante')], default='faltante', max_length=20, verbose_name='Estado')),
                ('carga_habilitada', models.BooleanField(default=True, verbose_name='Carga Habilitada')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='migration.solicitante')),
            ],
            options={
                'verbose_name': 'Requisito',
                'verbose_name_plural': 'Requisitos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versión')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisado', 'Revisado'), ('faltante', 'Faltante')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='Archivo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='migration.requisito')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-version'],
            },
        ),
        migrations.AddConstraint(
            model_name='requisito',
            constraint=models.UniqueConstraint(fields=('solicitante', 'nombre'), name='uniq_solicitante_requisito'),
        ),
    ]
