# Generated by Django 6.0.1 on 2026-01-28 02:42

import migration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='nombre_archivo',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='ruta_archivo',
        ),
        migrations.AddField(
            model_name='documento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=migration.models.generar_ruta_documento, verbose_name='Archivo subido'),
        ),
    ]
