# Generated by Django 6.0.1 on 2026-01-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpeta',
            name='observaciones',
            field=models.TextField(blank=True, default='', verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='carpeta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('cerrada_aceptada', 'Cerrada Aceptada'), ('cerrada_rechazada', 'Cerrada Rechazada')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
