# Generated by Django 6.0.1 on 2026-01-27 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0002_agente_usuario_solicitante_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_visa', models.CharField(max_length=50, verbose_name='Tipo de Visa')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('aprobado', 'Aprobado'), ('cerrado', 'Cerrado')], default='abierto', max_length=20, verbose_name='Estado')),
                ('creada_en', models.DateTimeField(auto_now_add=True, verbose_name='Creada en')),
                ('actualizada_en', models.DateTimeField(auto_now=True, verbose_name='Actualizada en')),
                ('solicitante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carpeta', to='migration.solicitante')),
            ],
            options={
                'verbose_name': 'Carpeta',
                'verbose_name_plural': 'Carpetas',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Requisito')),
                ('estado', models.CharField(choices=[('faltante', 'Faltante'), ('pendiente', 'Pendiente'), ('revisado', 'Revisado')], default='faltante', max_length=20, verbose_name='Estado')),
                ('habilitado_para_subir', models.BooleanField(default=True, verbose_name='Habilitado para Subir')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='migration.carpeta')),
            ],
            options={
                'verbose_name': 'Requisito',
                'verbose_name_plural': 'Requisitos',
                'ordering': ['nombre'],
                'unique_together': {('carpeta', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/%Y/%m/', verbose_name='Archivo')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versión')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones del Agente')),
                ('aprobado', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('subido_en', models.DateTimeField(auto_now_add=True, verbose_name='Subido en')),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='migration.requisito')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-version', '-subido_en'],
            },
        ),
    ]
