# Generated by Django 6.0.1 on 2026-01-28 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0002_carpeta_observaciones_alter_carpeta_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última actualización'),
        ),
        migrations.AddField(
            model_name='agente',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='agente',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='agente',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agente', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
