# Generated by Django 6.0.1 on 2026-01-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0003_agente_actualizado_en_agente_creado_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoRequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
            ],
            options={
                'verbose_name': 'Catálogo de Requisito',
                'verbose_name_plural': 'Catálogo de Requisitos',
                'ordering': ['nombre'],
            },
        ),
    ]
