# Generated by Django 6.0.1 on 2026-01-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0004_catalogorequisito'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Identificador único del tipo de visa (ej: estudiantil, trabajo)', max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del tipo de visa', max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
            ],
            options={
                'verbose_name': 'Tipo de Visa',
                'verbose_name_plural': 'Tipos de Visa',
                'ordering': ['nombre'],
            },
        ),
    ]
