# Generated by Django 6.0.1 on 2026-01-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0005_tipovisa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitante',
            name='tipo_visa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Visa'),
        ),
    ]
