# Generated by Django 6.0.1 on 2026-02-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0006_update_solicitante_tipo_visa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'pendiente'), ('pendiente_subir', 'pendiente por subir'), ('revisado', 'revisado'), ('rechazado', 'rechazado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'pendiente'), ('pendiente_subir', 'pendiente por subir'), ('revisado', 'revisado'), ('rechazado', 'rechazado')], default='pendiente_subir', max_length=20, verbose_name='Estado'),
        ),
    ]
